'use server'

import payload from 'payload'

/**
 * Reset a user's password using the token generated by the forgot password flow.
 */
export async function resetPassword(token: string, password: string): Promise<void> {
  await payload.resetPassword({
    token,
    password,
    collection: 'users',
  })
}
