'use client'

import React, { useState } from 'react'
import { SearchIcon, ArrowRight } from 'lucide-react'
import { FadeUp } from '@/components/motion/FadeUp'
import { EmptyState } from '@/components/shared/EmptyState'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import Link from 'next/link'
import {
  Accordion,
  AccordionItem,
  AccordionTrigger,
  AccordionContent,
} from '@/components/ui/accordion'

interface FaqAccordionItem {
  q: string
  a: string
  links?: { label: string; href: string }[]
}

const FAQ_DATA: { title: string; items: FaqAccordionItem[] }[] = [
  {
    title: 'About Longevia Research & Our Mission',
    items: [
      { q: 'What is Longevia Research?', a: 'Longevia Research is a premier US-based supplier of research-grade peptides and biochemicals. We are dedicated to providing the scientific community with the highest purity compounds, backed by independent third-party testing, to accelerate laboratory discovery.' },
      { q: 'What sets Longevia Research apart from other suppliers?', a: 'Our commitment to absolute transparency. Every compound we sell is synthesized in ISO-certified US laboratories and independently verified for ≥99% HPLC purity. We do not sell overseas-sourced raw powders, and every order ships with a lot-specific Certificate of Analysis.' },
      { q: 'Are your research compounds safe for human use?', a: 'No. All products sold by Longevia Research are strictly for in-vitro laboratory research and scientific study only. They are not intended for human consumption, aesthetic treatment, or clinical application.' },
      { q: 'Who typically purchases from Longevia Research?', a: 'Our clients range from independent academic researchers and university laboratories to commercial biotechnology firms studying tissue repair, metabolic pathways, and cellular health mechanisms.' }
    ]
  },
  {
    title: 'Products, Compounds & Purity Standards',
    items: [
      { q: 'What is research-use-only?', a: 'Research-use-only (RUO) means a product is intended exclusively for in-vitro laboratory research, scientific investigation, and educational study. RUO products are not drugs, supplements, or food products. They have not been evaluated by the FDA for safety or efficacy in humans and are not approved for human consumption, clinical diagnosis, or therapeutic use. All products sold by Longevia Research carry this designation and ship with explicit RUO labeling on every vial and package.' },
      { q: 'What purity level is research-grade?', a: 'Research-grade peptides must meet or exceed ≥99% HPLC purity to be considered suitable for reliable laboratory research. At Longevia Research, we enforce a strict non-negotiable ≥99% purity floor across our entire catalog. Every production batch is independently tested by third-party laboratories using High-Performance Liquid Chromatography (HPLC) and Liquid Chromatography–Mass Spectrometry (LC-MS). Any batch that fails to meet this threshold is immediately discarded and never fulfilled.', links: [{ label: 'How to read a peptide COA', href: '/journal/peptide-coa-hplc-purity-testing-guide' }] },
      { q: 'How are COAs verified?', a: 'Every Certificate of Analysis (COA) we provide is generated by an independent, third-party analytical laboratory — not in-house testing. Each COA includes HPLC purity results, LC-MS molecular identity confirmation, and endotoxin testing data, all traceable to a specific batch lot number. Our complete COA library is publicly accessible at /certificates. You can verify any compound’s full documentation before and after ordering.', links: [{ label: 'COA Library', href: '/certificates' }, { label: 'How to read a peptide COA', href: '/journal/peptide-coa-hplc-purity-testing-guide' }] },
      { q: 'Where are your compounds synthesized?', a: 'All compounds sold by Longevia Research are synthesized in ISO-certified, US-based peptide laboratories using solid-phase peptide synthesis (SPPS). We do not source raw powders from overseas suppliers. Our closed-loop US supply chain provides complete molecular traceability from synthesis to shipment — a meaningful differentiator from vendors who synthesize offshore and only fulfill domestically.' },
      { q: 'What compounds are available in your catalog?', a: 'Our catalog includes 24+ research-grade compounds across eight categories: Recovery (BPC-157, TB-500), Cellular Health (GHK-Cu, Humanin), Growth Factor (CJC-1295, Ipamorelin, Sermorelin), Metabolic (Semaglutide, MOTS-C, AOD-9604), Bioregulators (Epithalon, Thymalin), Cognitive Function (Semax, Selank), Receptor Agonist (PT-141, Melanotan II), and Essentials (NAD+, DSIP). All products are strictly for laboratory research use only.' }
    ]
  },
  {
    title: 'Peptide Science: HPLC, COA & Testing Methods',
    items: [
      { q: 'What is HPLC purity testing?', a: 'HPLC — High-Performance Liquid Chromatography — is an analytical testing method that separates a compound mixture by molecular properties to measure the concentration of the target peptide versus any impurities. The result is expressed as a percentage. A ≥99% HPLC purity result means 99% or more of the sample is the intended compound, with ≤1% consisting of degradation products or synthesis byproducts. It is the industry standard for verifying research peptide quality.', links: [{ label: 'Full HPLC & COA guide', href: '/journal/peptide-coa-hplc-purity-testing-guide' }] },
      { q: 'What is a Certificate of Analysis (COA)?', a: 'A Certificate of Analysis (COA) is a formal document from an independent laboratory confirming the quality and identity of a specific production batch. For research peptides, a standard COA includes: HPLC purity percentage, LC-MS mass spectrometry identity confirmation, batch lot number, endotoxin testing results, and the laboratory’s accreditation details. A COA from an independent third-party lab (not the manufacturer’s own testing) is the gold standard for verification.', links: [{ label: 'How to read a peptide COA', href: '/journal/peptide-coa-hplc-purity-testing-guide' }, { label: 'COA Library', href: '/certificates' }] },
      { q: 'What is lyophilization?', a: 'Lyophilization — also called freeze-drying — is a process that removes moisture from a peptide solution by freezing it and then applying a vacuum to convert the ice directly to vapor, leaving behind a stable, dry powder. Lyophilized peptides are significantly more stable during shipping and long-term storage than liquid formulations. Most research peptide vials are lyophilized for this reason. Reconstitution with bacteriostatic water is required before use in laboratory applications.', links: [{ label: 'Reconstitution & storage guide', href: '/journal/peptide-reconstitution-storage-guide' }] },
      { q: 'What is bacteriostatic water?', a: 'Bacteriostatic water (BAC water) is sterile water containing 0.9% benzyl alcohol, which acts as a preservative by inhibiting the growth of bacteria, yeast, and mold. It is the standard diluent for reconstituting lyophilized research peptides because the preservative properties extend the stability of the reconstituted solution significantly compared to sterile water alone. Most reconstituted peptides remain stable for 2–4 weeks when stored at 2–8°C using BAC water.', links: [{ label: 'Reconstitution & storage guide', href: '/journal/peptide-reconstitution-storage-guide' }, { label: 'Shop BAC Water', href: '/products/bac-water' }] }
    ]
  },
  {
    title: 'Ordering, Shipping & Fulfillment',
    items: [
      { q: 'Do you ship internationally?', a: 'Yes, we ship internationally from our US-based fulfillment facilities to most countries. International customers are responsible for understanding their country’s import regulations for research-use-only laboratory compounds. All international shipments include required RUO documentation on every vial and package. Delivery timeframes vary by destination; contact our support team at /contact for country-specific shipping estimates and restrictions.' },
      { q: 'What is the cutoff time for same-day shipping?', a: 'Orders placed before 2:00 PM Eastern Time (ET) on business days are fulfilled and shipped the same day from our US-based facilities. Orders placed after 2:00 PM ET, or on weekends and US public holidays, ship on the next available business day. Expedited 2-day delivery is available on all orders over $300 within the continental United States.' },
      { q: 'Is a signature required for delivery?', a: 'Signature requirements depend on the shipping option selected at checkout and the carrier’s local delivery protocols. Expedited orders and orders above certain value thresholds may require a signature upon delivery. If you need to arrange a specific delivery or signature requirement, contact our support team before placing your order and we will advise on the best option for your location.' },
      { q: 'How are peptides packaged and shipped?', a: 'All lyophilized research peptide vials are vacuum-sealed and shipped in protective padded packaging. Lyophilized (freeze-dried) peptides do not require cold-chain shipping because they are stable in dry powder form at ambient temperatures during transit. For reconstituted or temperature-sensitive compounds, we use validated insulated cold-chain packaging. Every shipment includes batch documentation and RUO labeling as required.' }
    ]
  },
  {
    title: 'Returns, Damage & Order Guarantees',
    items: [
      { q: 'Can I return an open vial?', a: 'Open research peptide vials cannot be returned due to the nature of laboratory research compounds and the integrity requirements of our quality assurance protocols. Once a vial seal is broken, we cannot verify the storage conditions, sterility, or chain of custody of the compound. If you have a concern about an unopened product or an order that does not match your documentation, contact our support team and we will review your case.' },
      { q: 'My order arrived damaged, what should I do?', a: 'If your order arrives with a damaged vial, broken seal, or any visible compromise to the packaging, contact our support team immediately at /contact with your order number and photographs of the damaged packaging. We take transit damage seriously and will arrange a replacement shipment. Do not use any compound from a vial with a compromised seal or that shows visible contamination.' },
      { q: 'What is your return or refund policy?', a: 'Due to the strict quality control, stability, and handling requirements of research-grade compounds, all sales are final and refunds or returns are not applicable. Once a product leaves our facility, its chain of custody and storage conditions can no longer be verified. However, if an order arrives damaged in transit or does not match the documented COA specification, we will issue a replacement at no cost.', links: [{ label: 'Full Refund & Returns Policy', href: '/refund' }] }
    ]
  },
  {
    title: 'Research Use, Storage & Compliance',
    items: [
      { q: 'Can I use these for human consumption?', a: 'No. All products sold by Longevia Research are strictly for laboratory and research use only. They are not intended for human consumption, clinical diagnosis, therapeutic application, or veterinary use. These statements have not been evaluated by the FDA. Customers purchasing research compounds confirm they are qualified researchers and will use products exclusively in compliance with applicable federal, state, and local regulations.' },
      { q: 'Are research peptides legal to buy in the USA?', a: 'Research peptides sold for in-vitro laboratory use are legal to purchase in the United States when they are properly labeled as research-use-only (RUO), not intended for human use, and sold to qualified researchers for legitimate scientific purposes. Longevia Research complies with all applicable federal and state regulations governing the sale of RUO laboratory compounds. It is the purchaser’s responsibility to comply with local regulations in their jurisdiction.' },
      { q: 'How should I store unmixed peptides?', a: 'Store lyophilized (unreconstituted) research peptide powder in a freezer at −20°C or below for long-term stability. Lyophilized peptides are resilient in dry form — brief room-temperature exposure during transit does not cause significant degradation. Avoid repeated freeze-thaw cycles, which can compromise structural integrity over time. Once received, transfer to the freezer promptly.', links: [{ label: 'Full reconstitution & storage guide', href: '/journal/peptide-reconstitution-storage-guide' }] },
      { q: 'How do I reconstitute a research peptide?', a: 'Use our free Peptide Reconstitution Calculator at /peptide-calculator for exact measurements. The standard process: draw the required volume of bacteriostatic water (BAC water) into a sterile syringe, inject slowly along the inner wall of the vial (never directly onto the powder), and gently swirl until fully dissolved. Do not shake. Refer to the step-by-step guide on the calculator page for syringe sizing, concentration formulas, and IU markings.', links: [{ label: 'Peptide Reconstitution Calculator', href: '/peptide-calculator' }, { label: 'Full reconstitution & storage guide', href: '/journal/peptide-reconstitution-storage-guide' }] },
      { q: 'How long do reconstituted peptides stay stable?', a: 'Once mixed with bacteriostatic water, most reconstituted research peptides remain stable for 2 to 4 weeks when stored upright in a refrigerator at 2–8°C. Bacteriostatic water extends shelf life significantly by inhibiting microbial growth via its 0.9% benzyl alcohol content. Never freeze a reconstituted peptide solution. If your solution becomes cloudy, discolored, or shows visible particulates, discard it and reconstitute a fresh vial.', links: [{ label: 'Full reconstitution & storage guide', href: '/journal/peptide-reconstitution-storage-guide' }] }
    ]
  },
  {
    title: 'Account, COA Access & Support',
    items: [
      { q: 'How do I access my past COAs?', a: 'All active batch Certificates of Analysis are publicly accessible in our COA Library at /certificates. Every order includes a batch lot number printed on the vial label — enter this number in the library to retrieve the specific documentation for your batch. If you need a COA for an order that is no longer active in the library or cannot locate your batch number, contact our support team at /contact and we will retrieve the documentation directly.', links: [{ label: 'COA Library', href: '/certificates' }, { label: 'How to read a peptide COA', href: '/journal/peptide-coa-hplc-purity-testing-guide' }] },
      { q: 'How do I reset my password?', a: 'To reset your account password, click the Login button in the top navigation and select "Forgot Password". Enter the email address associated with your account and you will receive a reset link within a few minutes. If you do not receive the email, check your spam folder or contact our support team at /contact for assistance.' },
      { q: 'How do I contact customer support?', a: 'Our support team is available via the Contact page at /contact. We respond to all enquiries within 1 business day. For the fastest response, include your order number and a brief description of your question. For batch or COA-specific queries, include the lot number from your vial label. You can also reach us via our social channels listed in the footer.' }
    ]
  }
]

export default function FaqClient() {
  const [searchQuery, setSearchQuery] = useState('')

  const filteredCategories = FAQ_DATA.map(cat => {
    return {
      ...cat,
      items: cat.items.filter(item => 
        item.q.toLowerCase().includes(searchQuery.toLowerCase()) || 
        item.a.toLowerCase().includes(searchQuery.toLowerCase())
      )
    }
  }).filter(cat => cat.items.length > 0)

  return (
    <main className="bg-[#f3f4f6] min-h-screen pb-24 flex flex-col">
      <div className="w-full max-w-2xl mx-auto pt-32 px-6 lg:px-12 flex-shrink-0">
        <nav aria-label='breadcrumb' className="text-xs font-mono tracking-widest uppercase text-ink/50">
          <Link href='/' className="hover:text-ink transition-colors">Home</Link>
          <span className="mx-2">›</span>
          <span className="text-ink">FAQ</span>
        </nav>
      </div>

      {/* Header & Search */}
      <section className="px-6 mb-16 lg:mb-24 mt-12 max-w-2xl mx-auto flex flex-col items-center flex-1">
        <FadeUp className="w-full flex flex-col items-center">
          <span className="px-4 py-1.5 bg-white border border-gray-100 shadow-sm text-ink rounded-full text-xs font-bold uppercase tracking-widest mb-6">Support Center</span>
          <h1 className="sr-only">Research Peptide FAQ — Your Questions Answered</h1>
          <div aria-hidden="true" className="text-4xl md:text-5xl lg:text-6xl font-bold text-ink mb-6 text-center tracking-tight leading-tight">
            Frequently Asked Questions
          </div>
          <p className="text-lg lg:text-xl text-gray-500 text-center mb-10 max-w-xl font-light leading-relaxed">
            Everything you need to know about our research-grade peptides, longevia, purity standards, COA verification, ordering, shipping, and research use guidelines. Browse by category below or use the search above.
          </p>
          
          <div className="relative w-full max-w-[540px]">
            <SearchIcon className="absolute left-6 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
            <Input 
              type="text" 
              placeholder="Search questions about peptides, longevia, ordering, and more..." 
              className="w-full h-14 pl-14 pr-6 rounded-full bg-white border-transparent shadow-sm hover:shadow-md focus:border-[#5984c4] focus:ring-1 focus:ring-[#5984c4] transition-all duration-300 text-lg placeholder:text-gray-400"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
            />
          </div>
        </FadeUp>
      </section>

      {/* FAQ Accordions */}
      <section className="px-4 md:px-6 max-w-[800px] mx-auto mb-24 w-full">
        <FadeUp delay={0.1}>
          {filteredCategories.length === 0 ? (
            <div className="py-24 bg-white rounded-[2rem] shadow-sm flex items-center justify-center">
              <EmptyState 
                icon={SearchIcon} 
                title="No results found" 
                description={`We couldn't find any answers matching "${searchQuery}".`} 
              />
            </div>
          ) : (
            <div className="flex flex-col gap-8">
              {filteredCategories.map((category) => (
                <div key={category.title} className="bg-white rounded-[1.5rem] lg:rounded-[2rem] p-6 lg:p-10 shadow-sm">
                  <div className="flex items-center gap-3 mb-8">
                    <div className="w-8 h-8 rounded-full bg-[#5984c4]/10 flex items-center justify-center shrink-0">
                      <div className="w-2.5 h-2.5 rounded-full bg-[#5984c4]" />
                    </div>
                    <h2 className="text-2xl lg:text-3xl font-bold text-ink tracking-tight">{category.title}</h2>
                  </div>
                  <Accordion type="multiple" className="w-full">
                    {category.items.map((item, i) => (
                      <AccordionItem key={i} value={`${category.title}-${i}`} className="border-b border-gray-100 last:border-0">
                        <AccordionTrigger className="text-lg md:text-xl font-medium text-ink hover:text-[#5984c4] transition-colors duration-300 py-6 text-left">
                          {item.q}
                        </AccordionTrigger>
                        <AccordionContent className="text-base md:text-lg text-gray-500 leading-relaxed pb-8 font-light">
                          <p>{item.a}</p>
                          {item.links && item.links.length > 0 && (
                            <div className="flex flex-wrap gap-x-6 gap-y-2 mt-4">
                              {item.links.map((link) => (
                                <Link key={link.href} href={link.href} className="text-sm font-medium text-[#5984c4] underline hover:text-ink transition-colors">
                                  {link.label} →
                                </Link>
                              ))}
                            </div>
                          )}
                        </AccordionContent>
                      </AccordionItem>
                    ))}
                  </Accordion>
                </div>
              ))}
            </div>
          )}
        </FadeUp>
      </section>

      {/* Bottom CTA Strip */}
      <section className="px-4 md:px-6 max-w-[800px] mx-auto w-full">
        <FadeUp delay={0.2}>
          <div className="bg-white rounded-[1.5rem] lg:rounded-[2rem] p-8 lg:p-12 shadow-sm text-center flex flex-col items-center">
            <h3 className="text-2xl md:text-3xl font-serif text-ink mb-4">Still have a question?</h3>
            <p className="text-gray-500 text-lg mb-8 max-w-lg leading-relaxed">
              Our support team responds within 1 business day. For compound-specific questions, our Journal also covers BPC-157, TB-500, GHK-Cu, and Semaglutide in detail.
            </p>
            <div className="flex flex-col md:flex-row flex-wrap items-center justify-center gap-4 w-full">
              <Link href="/contact" className="w-full md:w-auto flex-1 md:flex-none">
                <Button className="w-full whitespace-nowrap rounded-full px-8 h-14 bg-ink text-white hover:bg-[#5984c4] transition-colors duration-500 font-medium text-base flex items-center justify-center gap-2 group">
                  Contact Support
                  <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform shrink-0" />
                </Button>
              </Link>
              <Link href="/journal" className="w-full md:w-auto flex-1 md:flex-none">
                <Button variant="outline" className="w-full whitespace-nowrap rounded-full px-8 h-14 border-slate-200 text-ink hover:border-[#5984c4] hover:bg-slate-50 transition-colors duration-500 font-medium text-base flex items-center justify-center gap-2 group">
                  Explore the Journal
                  <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform shrink-0" />
                </Button>
              </Link>
              <Link href="/shop" className="w-full md:w-auto flex-1 md:flex-none">
                <Button variant="outline" className="w-full whitespace-nowrap rounded-full px-8 h-14 border-slate-200 text-ink hover:border-[#5984c4] hover:bg-slate-50 transition-colors duration-500 font-medium text-base flex items-center justify-center gap-2 group">
                  Browse Research Peptides
                  <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform shrink-0" />
                </Button>
              </Link>
            </div>
          </div>
        </FadeUp>
      </section>
    </main>
  )
}
