import type { Metadata } from 'next'
import FaqClient from './FaqClient'

const siteUrl = (process.env.NEXT_PUBLIC_SERVER_URL || 'https://www.thelooksmaxxinglab.com').replace(/\/+$/, '')

export const metadata: Metadata = {
  title: 'Research Peptide FAQ | Purity, Ordering & Storage',
  description: 'Answers to every question about research peptides, looksmaxxing, purity standards, COA verification, ordering, and storage. US-synthesized compounds. Research use only.',
  alternates: {
    canonical: `${siteUrl}/faq`,
  },
  openGraph: {
    images: [{ url: '/og/og-faq.webp', width: 1200, height: 630, alt: 'Research Peptide FAQ — The Looksmaxxing Lab' }],
    title: 'Research Peptide FAQ | The Looksmaxxing Lab',
    description: 'Frequently asked questions about research peptides, purity standards, COA verification, ordering, and storage.',
    url: `${siteUrl}/faq`,
  },
}

export default function FAQPage() {
  const schemaBreadcrumbList = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": [
      {
        "@type": "ListItem",
        "position": 1,
        "name": "Home",
        "item": "https://www.thelooksmaxxinglab.com"
      },
      {
        "@type": "ListItem",
        "position": 2,
        "name": "FAQ",
        "item": "https://www.thelooksmaxxinglab.com/faq"
      }
    ]
  };

  const schemaFAQPage = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": [
      {
        "@type": "Question",
        "name": "What is looksmaxxing?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Looksmaxxing is the practice of systematically optimizing physical appearance through controllable habits — skincare, grooming, fitness, nutrition, and sleep. The Looksmaxxing Lab focuses on evidence-based softmaxxing. All research products are strictly for laboratory use only."
        }
      },
      {
        "@type": "Question",
        "name": "What does research-use-only (RUO) mean?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Research-use-only (RUO) means a product is intended exclusively for laboratory research. RUO products are not drugs or supplements. They have not been evaluated by the FDA for human use and are not intended for human consumption, diagnosis, or treatment."
        }
      },
      {
        "@type": "Question",
        "name": "What purity level is research-grade?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Research-grade peptides must meet or exceed 99% HPLC purity. The Looksmaxxing Lab enforces a strict 99%+ purity floor verified by independent third-party HPLC and LC-MS testing on every production batch."
        }
      },
      {
        "@type": "Question",
        "name": "How are COAs verified?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Every COA is generated by an independent third-party laboratory including HPLC purity, LC-MS identity confirmation, endotoxin testing, and batch lot number. The full COA library is publicly accessible at /certificates."
        }
      },
      {
        "@type": "Question",
        "name": "What is the cutoff time for same-day shipping?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Orders placed before 2:00 PM Eastern Time on business days ship the same day. Orders after 2 PM ET or on weekends ship the next business day. 2-day delivery available on orders over $300."
        }
      },
      {
        "@type": "Question",
        "name": "Can I use these for human consumption?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "No. All products are strictly for laboratory and research use only. Not intended for human consumption, clinical diagnosis, or therapeutic use. These statements have not been evaluated by the FDA."
        }
      },
      {
        "@type": "Question",
        "name": "How should I store unmixed peptides?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Store lyophilized peptide powder in a freezer at -20°C or below for long-term stability. Avoid repeated freeze-thaw cycles. Once reconstituted with bacteriostatic water, refrigerate at 2-8°C and use within 2-4 weeks."
        }
      },
      {
        "@type": "Question",
        "name": "Is looksmaxxing safe?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Evidence-based softmaxxing — skincare, grooming, fitness, and healthy lifestyle — is safe and widely practised. Concerns arise with hardmaxxing approaches promoting extreme modification. Our research compounds are for laboratory use only, not for self-administration."
        }
      },
      {
        "@type": "Question",
        "name": "What is HPLC purity testing?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "HPLC (High-Performance Liquid Chromatography) separates a compound mixture to measure the concentration of the target peptide vs impurities, expressed as a percentage. A 99%+ result means 99% or more of the sample is the intended compound."
        }
      },
      {
        "@type": "Question",
        "name": "What is bacteriostatic water?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Bacteriostatic water (BAC water) is sterile water containing 0.9% benzyl alcohol that prevents microbial growth. It is the standard diluent for reconstituting lyophilized research peptides, extending reconstituted stability to 2-4 weeks at 2-8°C."
        }
      }
    ]
  };

  const schemaWebPage = {
    "@context": "https://schema.org",
    "@type": "WebPage",
    "name": "Research Peptide FAQ — The Looksmaxxing Lab",
    "url": "https://www.thelooksmaxxinglab.com/faq",
    "description": "Answers to questions about research peptides, looksmaxxing, purity, ordering, and compliance.",
    "mainEntity": schemaFAQPage
  };

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schemaBreadcrumbList) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schemaWebPage) }} />
      <FaqClient />
    </>
  )
}
